COL FUENTE FOR A300
SET LINES 300
SET PAGES 20000


select 'SELECT DBMS_METADATA.GET_DLL ('''|| OBJECT_TYPE ||''','''|| OBJECT_NAME ||''','''|| OWNER ||''') FROM DUAL;' FUENTE
FROM DBA_OBJECTS WHERE OBJECT_NAME LIKE 'QR_%' AND OBJECT_TYPE <> 'TABLE';
